"""Generate gbk_table.go from Python's standard CP936 codec."""

from pathlib import Path


def go_escape(character: str) -> str:
    code = ord(character)
    if character == "\\":
        return "\\\\"
    if character == '"':
        return '\\"'
    if 0x20 <= code <= 0x7E:
        return character
    return f"\\u{code:04x}"


def main() -> None:
    characters: list[str] = []
    for lead in range(0x81, 0xFF):
        for trail in list(range(0x40, 0x7F)) + list(range(0x80, 0xFF)):
            try:
                decoded = bytes((lead, trail)).decode("gbk")
            except UnicodeDecodeError:
                decoded = "\ufffd"
            if len(decoded) != 1:
                decoded = "\ufffd"
            characters.append(go_escape(decoded))

    chunks = ["".join(characters[index : index + 96]) for index in range(0, len(characters), 96)]
    lines = ["// Code generated by generate_gbk_table.py; DO NOT EDIT.", "package encoding", "", "const gbkMapping ="]
    lines.extend(f'\t"{chunk}" +' for chunk in chunks[:-1])
    lines.append(f'\t"{chunks[-1]}"')
    lines.append("")
    Path(__file__).with_name("gbk_table.go").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
