-- Four built-in, dependency-free table tools served by core-aitools:18669.
-- Each INSERT is idempotent so upgrades are safe on installations with repaired seed data.

SET NAMES utf8mb4;

INSERT INTO tool_box (tool_id,name,description,icon,user_id,app_id,end_point,`method`,web_schema,`schema`,visibility,deleted,create_time,update_time,is_public,favorite_count,usage_count,tool_tag,operation_id,creation_method,auth_type,top,source,display_source,avatar_color,status,version,temporary_data)
SELECT 'tool@tableextractv1','表格数据提取','读取 XLS、XLSX、CSV 并返回结构化数据','/aitools-files/icons/table-extract.svg','system','appid','http://core-aitools:18669/aitools/v1/table_extract','post',
'{"toolRequestInput":[{"id":"extract-url","name":"excel_url","description":"表格文件地址","type":"string","location":"body","required":true,"open":true,"from":2},{"id":"extract-sheet","name":"sheet_name","description":"工作表名称","type":"string","location":"body","required":false,"open":true,"from":2},{"id":"extract-range","name":"range","description":"单元格范围，例如 A1:D100","type":"string","location":"body","required":false,"open":true,"from":2},{"id":"extract-encoding","name":"encoding","description":"CSV 编码：auto、utf-8、gbk、gb2312","type":"string","location":"body","required":false,"default":"auto","open":true,"from":2}],"toolRequestOutput":[{"id":"out-code","name":"code","description":"状态码","type":"integer","open":true},{"id":"out-message","name":"message","description":"返回消息","type":"string","open":true},{"id":"out-sid","name":"sid","description":"会话 ID","type":"string","open":true},{"id":"out-data","name":"data","description":"结构化表格","type":"object","open":true}]}',
'{"openapi":"3.1.0","info":{"title":"表格数据提取","version":"1.0.0","x-is-official":true},"servers":[{"url":"http://core-aitools:18669"}],"paths":{"/aitools/v1/table_extract":{"post":{"operationId":"table_extract_v1","summary":"表格数据提取","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","properties":{"excel_url":{"type":"string"},"url":{"type":"string"},"sheet_name":{"type":"string"},"range":{"type":"string"},"encoding":{"type":"string","default":"auto"}}}}}},"responses":{"200":{"description":"success"}}}}}}',
0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,b'1',0,0,'table','table_extract_v1',1,0,0,1,'1,2','#1677FF',1,'V1.0',''
WHERE NOT EXISTS (SELECT 1 FROM tool_box WHERE tool_id='tool@tableextractv1');

INSERT INTO tool_box (tool_id,name,description,icon,user_id,app_id,end_point,`method`,web_schema,`schema`,visibility,deleted,create_time,update_time,is_public,favorite_count,usage_count,tool_tag,operation_id,creation_method,auth_type,top,source,display_source,avatar_color,status,version,temporary_data)
SELECT 'tool@tablebarv1','可视化图表-柱形图','根据结构化表格行生成 SVG 柱形图','/aitools-files/icons/bar-chart.svg','system','appid','http://core-aitools:18669/aitools/v1/bar_chart','post',
'{"toolRequestInput":[{"id":"bar-data","name":"data","description":"结构化表格行","type":"array-object","location":"body","required":true,"open":true,"from":2},{"id":"bar-category","name":"category_field","description":"分类字段；留空自动推断","type":"string","location":"body","required":false,"open":true,"from":2},{"id":"bar-values","name":"value_fields","description":"数值字段列表；留空自动推断","type":"array-string","location":"body","required":false,"open":true,"from":2},{"id":"bar-title","name":"title","description":"图表标题","type":"string","location":"body","required":false,"open":true,"from":2}],"toolRequestOutput":[{"id":"out-code","name":"code","type":"integer","open":true},{"id":"out-data","name":"data","description":"SVG 地址与字段映射","type":"object","open":true}]}',
'{"openapi":"3.1.0","info":{"title":"可视化图表-柱形图","version":"1.0.0","x-is-official":true},"servers":[{"url":"http://core-aitools:18669"}],"paths":{"/aitools/v1/bar_chart":{"post":{"operationId":"table_bar_v1","summary":"可视化图表-柱形图","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","required":["data"],"properties":{"data":{"type":"array","items":{"type":"object","additionalProperties":true}},"category_field":{"type":"string"},"value_fields":{"type":"array","items":{"type":"string"}},"title":{"type":"string"},"direction":{"type":"string","enum":["vertical","horizontal"]}}}}}},"responses":{"200":{"description":"success"}}}}}}',
0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,b'1',0,0,'table','table_bar_v1',1,0,0,1,'1,2','#FF5F91',1,'V1.0',''
WHERE NOT EXISTS (SELECT 1 FROM tool_box WHERE tool_id='tool@tablebarv1');

INSERT INTO tool_box (tool_id,name,description,icon,user_id,app_id,end_point,`method`,web_schema,`schema`,visibility,deleted,create_time,update_time,is_public,favorite_count,usage_count,tool_tag,operation_id,creation_method,auth_type,top,source,display_source,avatar_color,status,version,temporary_data)
SELECT 'tool@tablepiev1','可视化图表-饼图','根据结构化表格行生成 SVG 饼图或圆环图','/aitools-files/icons/pie-chart.svg','system','appid','http://core-aitools:18669/aitools/v1/pie_chart','post',
'{"toolRequestInput":[{"id":"pie-data","name":"data","description":"结构化表格行","type":"array-object","location":"body","required":true,"open":true,"from":2},{"id":"pie-category","name":"category_field","description":"分类字段；留空自动推断","type":"string","location":"body","required":false,"open":true,"from":2},{"id":"pie-value","name":"value_field","description":"数值字段；留空自动推断","type":"string","location":"body","required":false,"open":true,"from":2},{"id":"pie-donut","name":"donut","description":"是否生成圆环图","type":"boolean","location":"body","required":false,"default":false,"open":true,"from":2}],"toolRequestOutput":[{"id":"out-code","name":"code","type":"integer","open":true},{"id":"out-data","name":"data","description":"SVG 地址与字段映射","type":"object","open":true}]}',
'{"openapi":"3.1.0","info":{"title":"可视化图表-饼图","version":"1.0.0","x-is-official":true},"servers":[{"url":"http://core-aitools:18669"}],"paths":{"/aitools/v1/pie_chart":{"post":{"operationId":"table_pie_v1","summary":"可视化图表-饼图","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","required":["data"],"properties":{"data":{"type":"array","items":{"type":"object","additionalProperties":true}},"category_field":{"type":"string"},"value_field":{"type":"string"},"title":{"type":"string"},"donut":{"type":"boolean"}}}}}},"responses":{"200":{"description":"success"}}}}}}',
0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,b'1',0,0,'table','table_pie_v1',1,0,0,1,'1,2','#19C2C9',1,'V1.0',''
WHERE NOT EXISTS (SELECT 1 FROM tool_box WHERE tool_id='tool@tablepiev1');

INSERT INTO tool_box (tool_id,name,description,icon,user_id,app_id,end_point,`method`,web_schema,`schema`,visibility,deleted,create_time,update_time,is_public,favorite_count,usage_count,tool_tag,operation_id,creation_method,auth_type,top,source,display_source,avatar_color,status,version,temporary_data)
SELECT 'tool@excelgeneratev1','Excel表格生成','根据结构化表格行生成可下载 XLSX','/aitools-files/icons/excel-generate.svg','system','appid','http://core-aitools:18669/aitools/v1/excel_generate','post',
'{"toolRequestInput":[{"id":"excel-data","name":"data","description":"结构化表格行","type":"array-object","location":"body","required":true,"open":true,"from":2},{"id":"excel-columns","name":"columns","description":"列顺序；留空自动推断","type":"array-string","location":"body","required":false,"open":true,"from":2},{"id":"excel-sheet","name":"sheet_name","description":"工作表名称","type":"string","location":"body","required":false,"default":"Sheet1","open":true,"from":2},{"id":"excel-start","name":"start_cell","description":"写入起始单元格","type":"string","location":"body","required":false,"default":"A1","open":true,"from":2}],"toolRequestOutput":[{"id":"out-code","name":"code","type":"integer","open":true},{"id":"out-data","name":"data","description":"XLSX 地址与摘要","type":"object","open":true}]}',
'{"openapi":"3.1.0","info":{"title":"Excel表格生成","version":"1.0.0","x-is-official":true},"servers":[{"url":"http://core-aitools:18669"}],"paths":{"/aitools/v1/excel_generate":{"post":{"operationId":"excel_generate_v1","summary":"Excel表格生成","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","required":["data"],"properties":{"data":{"type":"array","items":{"type":"object","additionalProperties":true}},"columns":{"type":"array","items":{"type":"string"}},"sheet_name":{"type":"string"},"start_cell":{"type":"string"},"freeze_header":{"type":"boolean"},"auto_filter":{"type":"boolean"}}}}}},"responses":{"200":{"description":"success"}}}}}}',
0,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,b'1',0,0,'table','excel_generate_v1',1,0,0,1,'1,2','#12A36D',1,'V1.0',''
WHERE NOT EXISTS (SELECT 1 FROM tool_box WHERE tool_id='tool@excelgeneratev1');
